[[general-manage-billing]]
= Manage billing of your organization

// :description: Configure the billing details of your organization.
// :keywords: serverless, general, billing, overview

++++
<titleabbrev>Manage billing</titleabbrev>
++++

You can manage the billing details of your organization directly from the Elastic Cloud console. Bills are invoiced according to the billing contact and details that you set for your organization.

. Navigate to https://cloud.elastic.co/[cloud.elastic.co] and log in to your Elastic Cloud account.
. Go to the user icon on the header bar and select **Billing**.

From the **Billing pages**, you can perform the following tasks:

* <<general-check-subscription,Check your subscription overview>>
* <<general-monitor-usage,Monitor and analyze your account usage>>
* <<general-billing-history,Check your billing history>>

If you have a project that you're no longer using, refer to <<general-billing-stop-project,Stop charges for a project>>.

To learn about the serverless pricing model, refer to <<general-serverless-billing,Serverless billing dimensions>> and our https://www.elastic.co/pricing/serverless-search[pricing page].

[[general-billing-stop-project]]
== Stop charges for a project

// :description: How to stop charges for a project.
// :keywords: serverless, general, billing

preview:[]

Got a project you no longer need and don't want to be charged for? Simply delete it.

Warning: All data is lost. Billing for usage is by the hour and any outstanding charges for usage before you deleted the project will still appear on your next bill.

To stop being charged for a project:

. Log in to the {ess-console}[{ess-console-name}].
. Find your project on the home page in the **Serverless Projects** card and select **Manage** to access it directly. Or, select **Serverless Projects** to go to the projects page to view all of your projects.
. Select **Actions**, then select **Delete project** and confirm the deletion.
